# Shape: [theta,phi, theta_dot, phi_dot, rms_ch1, rms_ch2, rms_ch3, rms_ch4, nzc_ch1, nzc_ch2, nzc_ch3, nzc_ch4]
dimension: 2
order: second
controlled: false
step_size: 0.1 # features extracted every 100 ms = 0.1 s -> 10Hz
time_window: 1 # second
window_size: 15 # 1 second = int(twindow*fs)
window_step: 1

train:
  num_trajectories: 7
  position: true
  normalize_input: true
  normalize_output: false  
  padding: true
  load: 1
  num_epochs: 1000
  learning_rate: 1.0e-3
  weight_decay: 1.0e-6
  dynamic_lr: true
  verbose: true

test:
  train_data: true
  num_trajectories: 7
  duration: 30.0
  padding: true


model:
  net: lstm
  hidden_dim: 128
  preoutput_size: 20
  num_layers: 2
