dimension: 2
order: second
step_size: 0.01
window_size: 10
window_step: 1

simulate:
  num_trajectories: 10
  duration: 5.0
  grid_center: [3.14, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0] # spin, elevation, vel spin, vel elevation, ctr amp spin, ctr amp elevation. ctr phase spin, ctr phase elevation
  grid_size: [6.28, 3.14, 0.0, 0.0, 1.0, 1.0, 2.0, 2.0]

train:
  num_epochs: 200
  learning_rate: 1.0e-2
  weight_decay: 1.0e-6
  dynamic_lr: false
  verbose: true

test:
  num_trajectories: 1
  duration: 25.0
  grid_center: [0.0, 0.0, 0.0, 0.0]
  grid_size: [1.0, 1.0, 1.0, 1.0]

model:
  net: rnn
  hidden_dim: 128
  num_layers: 2
