dimension: 2
order: second
controlled: true
step_size: 0.01
window_size: 10 # for node this must be 1
window_step: 1

simulate:
  num_trajectories: 2
  duration: 5.0
  # spin, elevation, vel spin, vel elevation, ctr spin, ctr elevation
  # ctr amp spin, ctr amp elevation, ctr phase spin, ctr phase elevation
  grid_center: [3.14, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0]
  grid_size: [6.28, 3.14, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 2.0, 2.0]
  fixed_state: true

train:
  padding: true
  num_epochs: 1000
  learning_rate: 1.0e-2
  weight_decay: 0.0
  dynamic_lr: true
  verbose: true

test:
  train_data: true
  num_trajectories: 1
  duration: 5.0
  # spin, elevation, vel spin, vel elevation, ctr spin, ctr elevation
  # ctr amp spin, ctr amp elevation, ctr phase spin, ctr phase elevation
  grid_center: [3.14, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0]
  grid_size: [6.28, 3.14, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 2.0, 2.0]

model:
  net: lstm
  hidden_dim: 256
  num_layers: 2
