dimension: 2
step_size: 0.01
window_size: 10
window_step: 1

simulate:
  num_trajectories: 10
  duration: 25.0
  grid_length: [2.0, 2.0]
  grid_center: [0.0, 0.0]

train:
  num_epochs: 200
  learning_rate: 1.0e-2
  weight_decay: 1.0e-6
  dynamic_lr: false
  verbose: true

test:
  num_trajectories: 1
  duration: 25.0
  grid_length: [2.0, 2.0]
  grid_center: [0.0, 0.0]

model:
  net: rnn
  hidden_dim: 128
  num_layers: 2
